"""Pydantic models for banking transaction data and fraud alerts."""

from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from typing import Optional

from pydantic import BaseModel, field_validator


class Transaction(BaseModel):
    """Raw banking transaction domain model."""

    transaction_id: str
    account_id: str
    timestamp: datetime
    amount: Decimal
    transaction_type: str
    location: str
    status: str

    @field_validator("amount")
    @classmethod
    def validate_positive_amount(cls, v: Decimal) -> Decimal:
        if v <= 0:
            raise ValueError("Transaction amount must be positive")
        return v

    @field_validator("transaction_type")
    @classmethod
    def validate_type(cls, v: str) -> str:
        allowed = {"deposit", "withdrawal", "transfer", "payment"}
        if v.lower() not in allowed:
            raise ValueError(f"Transaction type must be one of: {allowed}")
        return v.lower()

    @field_validator("status")
    @classmethod
    def validate_status(cls, v: str) -> str:
        allowed = {"completed", "pending", "failed", "reversed"}
        if v.lower() not in allowed:
            raise ValueError(f"Status must be one of: {allowed}")
        return v.lower()


class TransactionRecord(BaseModel):
    """Enriched transaction record after ETL processing."""

    transaction_id: str
    account_id: str
    timestamp: datetime
    amount_original: Decimal
    amount_usd: Decimal
    transaction_type: str
    location: str
    status: str
    processing_date: str
    hour_of_day: int
    day_of_week: int
    is_weekend: bool


class FraudAlert(BaseModel):
    """Fraud alert generated by detection engine."""

    alert_id: str
    transaction_id: str
    account_id: str
    timestamp: datetime
    amount: Decimal
    fraud_type: str  # amount_threshold, rapid_consecutive, anomaly_score, velocity_check
    risk_score: float
    description: str
    detected_at: datetime